Repository ISC-MakeIT/javascript-100knocksV2, pull requests merged in 2019-07, with the labels that each got.

#87 Submit ken565609
  answer/example/HTML/01_helloTable/helloTable.html
  answer/ken565609/html/01/hellotable.html
Labels: please review

#86 html一問目とき終わりました
  answer/ryoga89/HTML/01_helloTable/hellotable.html
Labels: please review!

#84 js1~4
  README.md
  answer/example/CSS/10_drawing/annpannmann.html
  answer/example/CSS/10_drawing/face_kirby.html
  answer/example/CSS/10_drawing/morugana.html
  answer/example/JS/14_storage/storage.js
  answer/shinooooo/HTML/03_form/form.html
  answer/shinooooo/JS/01_wTime/wTime.css
  answer/shinooooo/JS/01_wTime/wTime.html
  answer/shinooooo/JS/01_wTime/wTime.js
  answer/shinooooo/JS/02_add/add.html
  answer/shinooooo/JS/03_toBin/toBin.html
  answer/shinooooo/JS/04_toHex/toHex.html
  img/drawing.PNG
Labels: please review

#85 JS6からです！
  answer/damegane/JS/02.add/02.html
  answer/damegane/JS/03.toBin/03.html
  answer/damegane/JS/06.bored/06.html
  answer/damegane/JS/06.bored/img/AWESOME.jpg
  answer/damegane/JS/06.bored/img/bored.jpg
  answer/damegane/JS/07.addImage/07.html
  answer/damegane/JS/07.addImage/img/nino.jpg
  answer/damegane/JS/07.addImage/img/nino1.jpg
  answer/damegane/JS/07.addImage/img/nino10.jpg
  answer/damegane/JS/07.addImage/img/nino11.jpg
  answer/damegane/JS/07.addImage/img/nino12.jpg
  answer/damegane/JS/07.addImage/img/nino13.jpg
  answer/damegane/JS/07.addImage/img/nino14.jpg
  answer/damegane/JS/07.addImage/img/nino15.jpg
  answer/damegane/JS/07.addImage/img/nino16.jpg
  answer/damegane/JS/07.addImage/img/nino17.jpg
  answer/damegane/JS/07.addImage/img/nino18.jpg
  answer/damegane/JS/07.addImage/img/nino19.jpg
  answer/damegane/JS/07.addImage/img/nino2.jpg
  answer/damegane/JS/07.addImage/img/nino20.jpg
  answer/damegane/JS/07.addImage/img/nino3.jpg
  answer/damegane/JS/07.addImage/img/nino4.jpg
  answer/damegane/JS/07.addImage/img/nino5.jpg
  answer/damegane/JS/07.addImage/img/nino6.jpg
  answer/damegane/JS/07.addImage/img/nino7.jpg
  answer/damegane/JS/07.addImage/img/nino8.jpg
  answer/damegane/JS/07.addImage/img/nino9.jpg
  answer/damegane/JS/08.createDiv/08.html
  answer/damegane/JS/09.switch/09.html
  answer/damegane/JS/09.switch/img/itika.jpg
  answer/damegane/JS/09.switch/img/ituki.jpg
  answer/damegane/JS/09.switch/img/miku.png
  answer/damegane/JS/09.switch/img/nino.jpg
  answer/damegane/JS/09.switch/img/yotuba.png
  answer/damegane/JS/10.3sec/10.html
  answer/damegane/JS/11.isSame/11.html
  answer/damegane/JS/12.sumSequence/12.html
  answer/damegane/JS/13.pulldown/13.html
  answer/damegane/JS/14.storage/14.html
  answer/damegane/JS/14.storage/14_2.html
  answer/damegane/JS/16.array1/16.html
  answer/damegane/JS/17.array2/17.html
Labels: please review!

#82 まとめて送ります。
  answer/salami/CSS/01_centerDiv/01_centerDiv.css
  answer/salami/CSS/01_centerDiv/01_centerDiv.html
  answer/salami/CSS/02_shadow/02_shadow.css
  answer/salami/CSS/02_shadow/02_shadow.html
  answer/salami/CSS/03_nav/03_nav.css
  answer/salami/CSS/03_nav/03_nav.html
  answer/salami/CSS/04_onImage/04.html
  answer/salami/CSS/04_onImage/04_onImage.css
  answer/salami/CSS/04_onImage/04_onImage.html
  answer/salami/CSS/04_onImage/551666a0078564e83e79f9a7353d826c.png
  answer/salami/CSS/05_new/05_new.css
  answer/salami/CSS/05_new/05_new.html
  answer/salami/CSS/06_float/06_float.css
  answer/salami/CSS/06_float/06_float.html
  answer/salami/CSS/07_flexbox/07_flexbox.css
  answer/salami/CSS/07_flexbox/07_flexbox.html
  answer/salami/CSS/08_CSS-Grid/08_CSS-Grid.css
  answer/salami/CSS/08_CSS-Grid/08_CSS-Grid.html
  answer/salami/CSS/08_CSS-Grid/img/abokado1.jpg
  answer/salami/CSS/08_CSS-Grid/img/abokado10.jpg
  answer/salami/CSS/08_CSS-Grid/img/abokado11.jpg
  answer/salami/CSS/08_CSS-Grid/img/abokado12.jpg
  answer/salami/CSS/08_CSS-Grid/img/abokado13.jpg
  answer/salami/CSS/08_CSS-Grid/img/abokado14.jpg
  answer/salami/CSS/08_CSS-Grid/img/abokado15.jpg
  answer/salami/CSS/08_CSS-Grid/img/abokado16.jpg
  answer/salami/CSS/08_CSS-Grid/img/abokado17.jpg
  answer/salami/CSS/08_CSS-Grid/img/abokado2.jpg
  answer/salami/CSS/08_CSS-Grid/img/abokado3.jpg
  answer/salami/CSS/08_CSS-Grid/img/abokado4.jpg
  answer/salami/CSS/08_CSS-Grid/img/abokado5.jpg
  answer/salami/CSS/08_CSS-Grid/img/abokado6.jpg
  answer/salami/CSS/08_CSS-Grid/img/abokado7.jpg
  answer/salami/CSS/08_CSS-Grid/img/abokado8.jpg
  answer/salami/CSS/08_CSS-Grid/img/abokado9.jpg
  answer/salami/HTML/01_helloTabel.html
  answer/salami/HTML/02_anchor.html
  answer/salami/HTML/03_form.html
Labels: please review!

#93 js05~07
  answer/shinooooo/JS/05_randomBgColor/randomBgColor.html
  answer/shinooooo/JS/06_bored/bored.html
  answer/shinooooo/JS/07_addImage/addImage.html
  answer/shinooooo/JS/07_addImage/heavenstime.gif
Labels: commented

#97 html問題1
  answer/56miyano/html/1_hellotable.html
Labels: please review

#99 html問題2
  answer/56miyano/html/2_anchor.html
Labels: commented

#100 Submit 56
  answer/56miyano/html/3_form.html
Labels: commented

#109 Submit ponpain
  answer/ponpain/CSS/01/centerDiv.html
  answer/ponpain/CSS/02/shadow.html
  answer/ponpain/CSS/03/nav.html
  answer/ponpain/CSS/04/Vice-City-1920x1080.png
  answer/ponpain/CSS/04/onImage.html
  answer/ponpain/CSS/05/new.html
  answer/ponpain/HTML/02/anchor.html
  answer/ponpain/HTML/03/form.html
Labels: please review!

#95 kitamumin
  answer/kitamura/JS/1/1wtime.html
  answer/kitamura/JS/12/sumSequence.html
  answer/kitamura/JS/13/pulldown.html
  answer/kitamura/JS/19/typeof.html
  answer/kitamura/JS/20/concat.html
  answer/kitamura/JS/21/join.html
  answer/kitamura/JS/22/rensouhairetu.html
  answer/kitamura/JS/23/wather.html
  answer/kitamura/JS/24/encrypto.html
  answer/kitamura/JS/25/decrypto.html
  answer/kitamura/JS/26/tanuki.html
  answer/kitamura/JS/27/duplicate.html
  answer/kitamura/JS/28/dupSort.html
  answer/kitamura/JS/28/dupSort.js
  answer/kitamura/JS/7/addimage.html
Labels: commented, please review!

#110 css一問目と二問目です。
  answer/ryoga89/CSS/01_centerDiv/centerDiv.css
  answer/ryoga89/CSS/01_centerDiv/centerDiv.html
  answer/ryoga89/CSS/02_shadow/shadow.css
  answer/ryoga89/CSS/02_shadow/shadow.html
  answer/ryoga89/HTML/01_helloTable/hellotable.html
Labels: commented, please review!
