Repository ISC-MakeIT/javascript-100knocksV2, pull requests merged in 2019-05, with the labels that each got.

#10 HTML1問目です
  zamadokaSchool/HTML1/HTML1.html
Labels: commented

#13 htmlの一問目
  okodayon/html 1/1.html
Labels: commented, please review!

#16 結果にコミットする。ライザップ
  html/html1/100knocks.html
  html/html1/9000.jpg
  html/html2/html.html
Labels: please review!

#11 html1もんめです
  luke2074/HTML1.html
Labels: commented

#12 Submit tsunakan0o0
  tsunakan0o0/HTML1.html
Labels: commented, please review!

#19 二問目でーす　jsむずかち
  okodayon/html 2/anchor.html
Labels: please review!

#29 解答手順修正(簡易的)
  answer/example/回答手順.md
Labels: please review!

#25 1問目です
  answer/kitamura/HTML/1/hellotable.css
  answer/kitamura/HTML/1/hellotable.html
Labels: please review!

#32 テストで1つコミットです
  answer/shinooooo/HTML/01_helloTable/hellotable.html
Labels: please review!

#22 HTML2問目です
  answer/tsunakan0o0/HTML2.html
Labels: commented, please review!

#31 Submit isshun226
  answer/isshun226/HTML/html1/1_HelloTable.html
  answer/isshun226/HTML/html2/2_Anchor.html
  answer/isshun226/HTML/html3/3_Form.html
Labels: commented

#33 html1問目
  answer/ponpain/HTML/01/hellotable.html
Labels: commented

#37 ADD INDET CI TESTS
  .circleci/config.yml
  .eslintrc.json
  .gitignore
  .htmllintrc
  .stylelintrc.json
  answer/example/HTML/02_anchor/anchor.html
Labels: NASU_TOP_SECRET
