Repository ISC-MakeIT/javascript-100knocksV2, pull requests merged in 2019-06, with the labels that each got.

#23 HTML2もんめです
  answer/luke2074/HTML2.html
Labels: commented

#30 100nocks
  100nocks166ryoryo/CSS/01/centerDiv.css
  100nocks166ryoryo/CSS/01/centerDiv.html
  100nocks166ryoryo/CSS/02/shadow.css
  100nocks166ryoryo/CSS/02/shadow.html
  100nocks166ryoryo/CSS/03/nav.css
  100nocks166ryoryo/CSS/03/nav.html
  100nocks166ryoryo/CSS/04/onlmage.css
  100nocks166ryoryo/CSS/04/onlmage.html
  100nocks166ryoryo/CSS/04/original.png
  100nocks166ryoryo/HTML/01/hello_Table.html
  100nocks166ryoryo/HTML/02/anchor.html
  100nocks166ryoryo/HTML/03/form.html
Labels: commented

#39 HTML3問目です
  answer/tsunakan0o0/HTML3.html
Labels: commented

#41 HTML2問目です
  zamadokaSchool/HTML2/HTML2.html
Labels: commented

#49 おそらく最後の手動コミット。HTML2問目
  answer/IZM168/2/100knocks2.html
Labels: please review!

#47 HTML3問目
  zamadokaSchool/HTML3/HTML3.html
Labels: please review!

#54 CSS1問目
  zamadokaSchool/CSS/CSS1/CSS01.css
  zamadokaSchool/CSS/CSS1/CSS01.html
  zamadokaSchool/HTML/HTML1/HTML1.html
  zamadokaSchool/HTML/HTML2/HTML2.html
  zamadokaSchool/HTML/HTML3/HTML3.html
Labels: commented

#56 CSS2問目です
  zamadokaSchool/CSS/CSS01/CSS01.css
  zamadokaSchool/CSS/CSS01/CSS01.html
  zamadokaSchool/CSS/CSS02/CSS02.css
  zamadokaSchool/CSS/CSS02/CSS02.html
Labels: please review!

#51 Submit shinooooo
  answer/shinooooo/CSS/01_centerDiv/centerDiv.css
  answer/shinooooo/CSS/01_centerDiv/centerDiv.html
  answer/shinooooo/HTML/01_helloTable/hellotable.html
  answer/shinooooo/HTML/02_anchor/anchor.html
  answer/shinooooo/HTML/03_form/form.html
Labels: commented, please review

#60 drawing問題修正
  README.md
  answer/example/CSS/10_drawing/annpannmann.html
  answer/example/CSS/10_drawing/face_kirby.html
  answer/example/CSS/10_drawing/morugana.html
  img/drawing.PNG
Labels: please review!

#61 画像のパスを削除
  answer/example/CSS/10_drawing/annpannmann.html
  answer/example/CSS/10_drawing/face_kirby.html
Labels: please review!

#52 Submit 166ryoryo
  100nocks166ryoryo/CSS/05/new.css
  100nocks166ryoryo/CSS/05/new.html
  100nocks166ryoryo/CSS/06/float.css
  100nocks166ryoryo/CSS/06/float.html
  100nocks166ryoryo/CSS/07/flexbox.css
  100nocks166ryoryo/CSS/07/flexbox.html
  100nocks166ryoryo/CSS/08/CSS_Grid.css
  100nocks166ryoryo/CSS/08/CSS_Grid.html
  100nocks166ryoryo/CSS/08/img/aiku.png
  100nocks166ryoryo/CSS/08/img/misuto.png
  100nocks166ryoryo/CSS/08/img/rete.png
  100nocks166ryoryo/CSS/08/img/senerio.png
  100nocks166ryoryo/CSS/08/img/sikkokunokishi.png
  100nocks166ryoryo/CSS/08/img/souen_a_1024-768-1024x768.jpg
  100nocks166ryoryo/CSS/08/img/thiba-n.png
  100nocks166ryoryo/CSS/09/position.css
  100nocks166ryoryo/CSS/09/position.html
  100nocks166ryoryo/CSS/10/drawing.css
  100nocks166ryoryo/CSS/10/drawing.html
  100nocks166ryoryo/CSS/10/ff.css
  100nocks166ryoryo/CSS/10/ff.html
  100nocks166ryoryo/CSS/10/omake.css
  100nocks166ryoryo/CSS/10/omake.html
  100nocks166ryoryo/CSS/10/pengin.css
  100nocks166ryoryo/CSS/10/pengin.html
  100nocks166ryoryo/JS/01/wTime.html
Labels: please review

#59 Submit shinooooo
  answer/shinooooo/CSS/01_centerDiv/centerDiv.css
  answer/shinooooo/CSS/01_centerDiv/centerDiv.html
  answer/shinooooo/CSS/02_shadow/shadow.html
  answer/shinooooo/CSS/03_nav/nav.html
  answer/shinooooo/CSS/04_onlmage/onImage.html
  answer/shinooooo/CSS/04_onlmage/usagi.jpg
  answer/shinooooo/HTML/03_form/form.html
Labels: commented, please review

#69 100nock 166ryoryo
  100nocks166ryoryo/CSS/10/omake.css
  100nocks166ryoryo/CSS/10/pi.css
  100nocks166ryoryo/CSS/10/pi.html
  100nocks166ryoryo/JS/01/wTime.html
  100nocks166ryoryo/JS/02/add.js
Labels: please review

#70 Submit shinooooo
  answer/shinooooo/CSS/05_new/new.css
  answer/shinooooo/CSS/05_new/new.html
  answer/shinooooo/CSS/06_float/float.css
  answer/shinooooo/CSS/06_float/float.html
  answer/shinooooo/CSS/07_flexbox/flexbox.css
  answer/shinooooo/CSS/07_flexbox/flexbox.html
Labels: commented, please review

#71 100nock 166ryoryo
  100nocks166ryoryo/CSS/10/pi.html
  100nocks166ryoryo/JS/02/add.js
  100nocks166ryoryo/JS/03/toBin.html
  100nocks166ryoryo/JS/04/toHex.html
  100nocks166ryoryo/JS/05/randomBgColor.html
Labels: please review!

#77 Submit kitamumin
  answer/kitamura/CSS/10/10drawing.html
  answer/kitamura/CSS/8/8cssgrid.css
  answer/kitamura/CSS/8/8cssgrid.html
  answer/kitamura/CSS/8/img/1.jpg
  answer/kitamura/CSS/8/img/2.jpg
  answer/kitamura/CSS/8/img/icon_bomber.png
  answer/kitamura/CSS/8/img/icon_burrows.png
  answer/kitamura/CSS/8/img/icon_caron.png
  answer/kitamura/CSS/8/img/icon_cybilla.png
  answer/kitamura/CSS/8/img/icon_noel.png
  answer/kitamura/CSS/9/9position.css
  answer/kitamura/CSS/9/9position.html
  answer/kitamura/JS/1/1wtime.html
  answer/kitamura/JS/2/2add.html
Labels: please review!

#76 Submit shinooooo
  answer/shinooooo/CSS/08_CSS_Grid/CSS_Grid.css
  answer/shinooooo/CSS/08_CSS_Grid/CSS_Grid.html
  answer/shinooooo/CSS/08_CSS_Grid/img/01.jpg
  answer/shinooooo/CSS/08_CSS_Grid/img/02.jpg
  answer/shinooooo/CSS/08_CSS_Grid/img/03.jpg
  answer/shinooooo/CSS/08_CSS_Grid/img/04.jpg
  answer/shinooooo/CSS/08_CSS_Grid/img/05.jpg
  answer/shinooooo/CSS/08_CSS_Grid/img/11.jpg
  answer/shinooooo/CSS/08_CSS_Grid/img/12.jpg
  answer/shinooooo/CSS/09_position/position.css
  answer/shinooooo/CSS/09_position/position.html
Labels: commented, please review

#81 Submit ponpain
  answer/ponpain/CSS/01/centerDiv.html
  answer/ponpain/CSS/02/shadow.html
  answer/ponpain/HTML/02/anchor.html
  answer/ponpain/HTML/03/form.html
Labels: commented

#83 CSS４問目から９問目までやりました
  answer/masaya2019/CSS/04/CSS/style.css
  answer/masaya2019/CSS/04/IMG/cat.jpg
  answer/masaya2019/CSS/04/onlmage.html
  answer/masaya2019/CSS/05/CSS/style.css
  answer/masaya2019/CSS/05/new.html
  answer/masaya2019/CSS/06/CSS/style.css
  answer/masaya2019/CSS/06/float.html
  answer/masaya2019/CSS/07/CSS/style.css
  answer/masaya2019/CSS/07/flexbox.html
  answer/masaya2019/CSS/08/CSS/style.css
  answer/masaya2019/CSS/08/IMG/ice.jpg
  answer/masaya2019/CSS/08/IMG/latte.jpg
  answer/masaya2019/CSS/08/IMG/matcha.png
  answer/masaya2019/CSS/08/IMG/ring.jpg
  answer/masaya2019/CSS/08/IMG/roll.jpg
  answer/masaya2019/CSS/08/IMG/soft.jpg
  answer/masaya2019/CSS/08/IMG/tart.png
  answer/masaya2019/CSS/08/cssGrid.html
  answer/masaya2019/CSS/09/CSS/style.css
  answer/masaya2019/CSS/09/position.html
  answer/masaya2019/HTML/02/anchor.html
Labels: please review!

#34 Submit damegane
  answer/damegane/CSS/01.centerDiv/01.css
  answer/damegane/CSS/01.centerDiv/01.html
  answer/damegane/CSS/02.shadow/02.css
  answer/damegane/CSS/02.shadow/02.html
  answer/damegane/CSS/03.nav/03.css
  answer/damegane/CSS/03.nav/03.html
  answer/damegane/CSS/04.onlmage/04.css
  answer/damegane/CSS/04.onlmage/04.html
  answer/damegane/CSS/04.onlmage/img/b18b912d69fa0b3d571054c8f5fda5cf.jpg
  answer/damegane/CSS/05.new/05.css
  answer/damegane/CSS/05.new/05.html
  answer/damegane/CSS/06.float/06.css
  answer/damegane/CSS/06.float/06.html
  answer/damegane/CSS/07.flexbox/07.css
  answer/damegane/CSS/07.flexbox/07.html
  answer/damegane/CSS/08.grid/08.css
  answer/damegane/CSS/08.grid/08.html
  answer/damegane/CSS/08.grid/img/itika.jpg
  answer/damegane/CSS/08.grid/img/ituki.jpg
  answer/damegane/CSS/08.grid/img/miku.jpg
  answer/damegane/CSS/08.grid/img/nino.jpg
  answer/damegane/CSS/08.grid/img/yotuba.jpg
  answer/damegane/CSS/08.grid/img/五等分してないやつ.jpg
  answer/damegane/CSS/09.position/09.css
  answer/damegane/CSS/09.position/09.html
  answer/damegane/HTML/01.helloTable/01.html
  answer/damegane/HTML/02.anchor/02.html
  answer/damegane/HTML/03.form/03.html
  answer/damegane/JS/01.wTime/01.html
  answer/damegane/JS/02.add/02.html
  answer/damegane/JS/03.toBin/03.css
  answer/damegane/JS/03.toBin/03.html
  answer/damegane/JS/04.toHex/04.html
  answer/damegane/JS/05.randomBgColor/05.html
  answer/damegane/JS/15.fizzbuzz/15.html
  answer/example/CSS/10_drawing/morugana.html
Labels: commented, please review!
