Repository ISC-MakeIT/javascript-100knocksV2, pull requests merged in 2019-08, with the labels that each got.

#112 Submit kitamumin
  answer/kitamura/JS/28/dupSort.js
  answer/kitamura/JS/29/dupDel.html
  answer/kitamura/JS/30/partOfTable.html
  answer/kitamura/JS/31/witchPlace.html
Labels: please review!

#91 JS途中
  answer/damegane/JS/18.array3/18.html
  answer/damegane/JS/19.typeof/19.html
  answer/damegane/JS/20.concat/20.html
  answer/damegane/JS/21.join/21.html
  answer/damegane/JS/22.rensouhairetu/22.html
  answer/damegane/JS/23.weather/23.html
  answer/damegane/JS/24.encrypto/24.html
  answer/damegane/JS/25.decrypto/25.html
  answer/damegane/JS/26.tanuki/26.html
  answer/damegane/JS/27.duplicate/27.html
  answer/damegane/JS/28.dupSort/28.html
  answer/damegane/JS/29.dupDel/29.html
  answer/damegane/JS/30. partOfTable/30.html
  answer/damegane/JS/31.tablePlease/31.html
  answer/damegane/jQuery/01.jquery/01.html
  answer/damegane/jQuery/02.incrementHello/02.html
  answer/damegane/jQuery/03.chageColor/03.html
  answer/damegane/jQuery/04.addImageJq/04.html
  answer/damegane/jQuery/04.addImageJq/img/nino.jpg
  answer/damegane/jQuery/05.hasImage/05.html
  answer/damegane/jQuery/06.selectImage/06.html
  answer/damegane/jQuery/07.removeImage/07.html
  answer/damegane/jQuery/07.removeImage/img/nino1.jpg
  answer/damegane/jQuery/07.removeImage/img/nino2.jpg
  answer/damegane/jQuery/07.removeImage/img/nino3.jpg
  answer/damegane/jQuery/07.removeImage/img/nino4.jpg
  answer/damegane/jQuery/07.removeImage/img/nino5.jpg
  answer/damegane/jQuery/jquery.js
  answer/example/JS/14_storage/storage.js
Labels: please review!

#106 Submit shinooooo
  answer/shinooooo/JS/01_wTime/wTime.js
  answer/shinooooo/JS/06_bored/bored.html
  answer/shinooooo/JS/07_addImage/addImage.html
  answer/shinooooo/JS/08_createDiv/createDiv.html
  answer/shinooooo/JS/09_switch/0.jpg
  answer/shinooooo/JS/09_switch/1.jpg
  answer/shinooooo/JS/09_switch/2.jpg
  answer/shinooooo/JS/09_switch/3.jpg
  answer/shinooooo/JS/09_switch/4.jpg
  answer/shinooooo/JS/09_switch/5.jpg
  answer/shinooooo/JS/09_switch/switch.html
  answer/shinooooo/JS/10_3sec/3sec.html
  answer/shinooooo/JS/11_isSame/isSame.html
  answer/shinooooo/JS/12_sumSquence/sumSquence.html
Labels: please review

#119 js13~20
  answer/shinooooo/JS/12_sumSquence/sumSquence.html
  answer/shinooooo/JS/13_pulldown/pulldown.html
  answer/shinooooo/JS/14_strage/strage.js
  answer/shinooooo/JS/14_strage/strage1.html
  answer/shinooooo/JS/14_strage/strage2.html
  answer/shinooooo/JS/15_fizzbuzz/fizzbuzz.html
  answer/shinooooo/JS/16_array1/array1.html
  answer/shinooooo/JS/17_array2/array2.html
  answer/shinooooo/JS/18_array3/array3.html
  answer/shinooooo/JS/19_typeof/typeof.html
  answer/shinooooo/JS/20_concat/concat.html
Labels: please review

#121 js21~31
  answer/shinooooo/JS/21_join/join.html
  answer/shinooooo/JS/22_rensouhairetu/rensouhairetu.html
  answer/shinooooo/JS/23_weather/weather.html
  answer/shinooooo/JS/24_encrypto/encrypto.html
  answer/shinooooo/JS/25_decrypto/decrypto.html
  answer/shinooooo/JS/26_tanuki/tanuki.html
  answer/shinooooo/JS/27_deplicate/deplicate.html
  answer/shinooooo/JS/28_dubSort/dubSort.html
  answer/shinooooo/JS/29_dupDel/dupDel.html
  answer/shinooooo/JS/30_partOfTable/partOfTable.html
  answer/shinooooo/JS/31_whichPlace/whichPlace.html
Labels: commented

#124 Submit kitamumin
  answer/kitamura/JQuery/1/jquery.html
  answer/kitamura/JQuery/2/incrementHello.html
  answer/kitamura/JQuery/3/changeColor.html
  answer/kitamura/JQuery/4/addImagejq.html
  answer/kitamura/JQuery/4/img/kokoro.jpg
  answer/kitamura/JQuery/5/hasImage.html
  answer/kitamura/JQuery/5/img/kokoro.jpg
  answer/kitamura/JQuery/6/img/kokoro.jpg
  answer/kitamura/JQuery/6/selectImage.html
  answer/kitamura/JQuery/7/img/kokoro.jpg
  answer/kitamura/JQuery/7/removeImage.html
Labels: please review!
